version: "3.8"

services:
  notes-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app           
      # - /app/node_modules 
      - ./cache:/app/cache
    environment:
      - NODE_ENV=delevopment
    command: npm start
    # command: nodemon index.js -- -h 0.0.0.0 -p 3000 -c ./cache
    # restart: always
    # command: >
    #   sh -c "echo '[]' > /app/cache && node index.js -h 0.0.0.0 -p 3000 -c /app/cache"
